env_type: wan_wm
task_suite_name: tower_of_hanoi_game
wm_env_type: yam

total_num_envs: null

auto_reset: False
ignore_terminations: False
max_steps_per_rollout_epoch: 250
max_episode_steps: 250

use_rel_reward: True
reward_coef: 1.0

reset_gripper_open: False
is_eval: False

seed: 0
group_size: 1
use_fixed_reset_state_ids: True
use_ordered_reset_state_ids: False
specific_reset_id: null

video_cfg:
  save_video: False
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

enable_offload: True

###  ------------------Wan params define here ------------------

wan_wm_hf_ckpt_path: null

VAE_path: ${env.train.wan_wm_hf_ckpt_path}/Wan2.2_VAE.pth
model_path: ${env.train.wan_wm_hf_ckpt_path}/model-00001.safetensors

enable_kir: False
use_latent_condition_cache: True
initial_image_path: ${env.train.wan_wm_hf_ckpt_path}/dataset/

subtasks:
  enabled: False
  sampling: grouped_random
  items: []

num_inference_steps: 5
action_dim: 14
chunk: 48
condition_frame_length: 5
wan_predict_frames: 8
action_downsample_stride: 6
image_size: [544, 320]
image_layout: vertical_3view_padded_bottom
view_height: 180
num_views: 3
padding_bottom: 4
num_frames: 13

reward_model:
  type: ResNetRewardModel
  from_pretrained: ${env.train.wan_wm_hf_ckpt_path}/full_weights.pt
  pretrained: False
  arch: resnet18
  hidden_dim: 256
  dropout: 0
  image_size: [3, 544, 320]
  normalize: True
  precision: fp32
  reward_threshold: 0.5
